---
# Pod Disruption Budget for backend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: punju-university
  labels:
    app: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
  unhealthyPodEvictionPolicy: AlwaysAllow

---
# Pod Disruption Budget for frontend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: punju-university
  labels:
    app: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
  unhealthyPodEvictionPolicy: AlwaysAllow

---
# Pod Disruption Budget for MongoDB
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongodb-pdb
  namespace: punju-university
  labels:
    app: mongodb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mongodb
  unhealthyPodEvictionPolicy: AlwaysAllow
